<!--<div data-widget data-app="6ati4ove2i5enu5avony" data-locale="fr"></div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
    $('[data-widget]').on('ready.rc.widget', function() {
//        $('.submit-button').hide();
//        
//        $('#sendButton').on('click', function(){
//            var session_id = $('[name="ringcaptcha_session_id"]').val();
//            console.log(session_id);
//        })
    });
    $('[data-widget]').on('pending.rc.widget', function(a) {
        
    });
</script>
<script src="//cdn.ringcaptcha.com/widget/v2/bundle.min.js"></script>
<input id="sendButton" type="button" value="Send">-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Ringcaptcha test form</title>
    <link rel="stylesheet" type="text/css" href="assets/view.css" media="all">
    <script type="text/javascript" src="assets/view.js"></script>
</head>
<body id="main_body" >
    <img id="top" src="assets/top.png" alt="">
    <div id="form_container">
        <h1><a>Ringcaptcha test form</a></h1>
        <form id="form_240153" class="appnitro"  method="post" action="">
            <div class="form_description">
                <h2>Ringcaptcha test form</h2>
                <p>Test our service here.</p>
            </div>
            <ul>
                <li id="li_2" >
                    <label class="description" for="element_2">Name </label>
                    <span>
                        <input id="element_2_1" name= "element_2_1" class="element text" maxlength="255" size="8" value=""/>
                        <label>First</label>
                    </span>
                    <span>
                        <input id="element_2_2" name= "element_2_2" class="element text" maxlength="255" size="14" value=""/>
                        <label>Last</label>
                    </span>
                </li>
                <li id="li_1" >
                    <label class="description" for="element_1">Email address: </label>
                    <div>
                        <input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/>
                    </div>
                </li>
                <li class="section_break">
                    <h3>Phone verification</h3>
                    <p>We want to know if you are a real person</p>
                </li>
                <li id="li_1" >
                    <!-- Paste here your widget code -->
                    <script type='text/javascript' charset='UTF-8' src='http://api.ringcaptcha.com/widget/6ati4ove2i5enu5avony'></script>
                </li>
                <li class="buttons">
                    <input type="hidden" name="form_id" value="240153" />
                    <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                </li>
            </ul>
        </form>
        <div id="footer">
            Generated by <a href="http://www.phpform.org">pForm</a>
        </div>
    </div>
    <img id="bottom" src="assets/bottom.png" alt="">
</body>
</html>